### PR TITLE
Remove `@cached` decorator and CACHE_MANAGER

### LINKED ISSUE #1780: Astroid is leaking memory
Astroid is leaking memory when is run multiple times over same file using API

### Steps to reproduce

1. Pick larger file, e.g. file from pylint project: pylint/checkers/variables.py
2. Run following script:
```python
from pylint.lint import Run
from pylint.lint import pylinter
while True:
    Run(["pylint/checkers/variables.py"], exit=False)
    pylinter.MANAGER.clear_cache()
```

### Current behavior

After ~12 iteration memory goes over 1 GB and keeps growing
image

### Expected behavior

Allocated memory should not rise indefinitelly

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output

2.13.0-dev0

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description
See discussion in #1780, much of the remaining leaking was due to having an inferior version of the stdlib's `@cached_property`. There's no reason to maintain a poorer version ourselves.

Closes #1780 

## Benchmark
From the script linked [here](https://github.com/pylint-dev/astroid/issues/1780#issuecomment-1465186635), I now see:

```
python3 memory.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


Nodes INC: 103014
Nodes NEW: 103014
Dicts INC: 55562
Dicts NEW: 55562

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


Nodes INC: 0
Nodes NEW: 103014
Dicts INC: 27
Dicts NEW: 55589

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


Nodes INC: 0
Nodes NEW: 103014
Dicts INC: 15
Dicts NEW: 55604

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


Nodes INC: 0
Nodes NEW: 103014
Dicts INC: 15
Dicts NEW: 55619

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


Nodes INC: 0
Nodes NEW: 103014
Dicts INC: 15
Dicts NEW: 55634
```

While "Dicts INC" isn't perfect (isn't 0), I think we've finished all the work we've identified so far, and I'm okay closing the linked issue.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Amazing !

**Comment by Pierre-Sassoulas** [comment]
I'm wondering if this should go in 2.15.2

**Comment by jacobtylerwalls** [comment]
I removed `@cached` without a deprecation warning. It will cause a few breakages in pylint. I know we're becoming more pragmatic about backwards compatibility in astroid, but if we're keeping to semantic versioning, let's not do it in a patch release. WDYT?

**Comment by Pierre-Sassoulas** [comment]
Ha ok, we're using it elsewhere too. I thought it was only used in astroid and replaced by a proper cache on the fly. Make sense !

**Pull request merged**
