### PR TITLE
Fix `collections.abc` imports on Python 3.13.0 and 3.13.1 (#2657)

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
Manual backport, conflicts were not so easy to solve, need a real review.

### CODE REVIEW

**Comment by DanielNoord** [comment]
We were missing https://github.com/pylint-dev/astroid/commit/71f5c0c84a4122edcb0fd638b284a0cf58a07a89 as it changed some of the variables names.

This should do the trick.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Can we release with PyPy failing?

**Comment by Pierre-Sassoulas** [comment]
I feel like pypy is failing half the time this days. So it dépends is if it's the usual flakyness or an actual issue. The one I Saw was a user warning not being raised..

**Comment by DanielNoord** [comment]
Shall we just merge this and at least try to unblock `pylint`?

**Comment by Pierre-Sassoulas** [comment]
Yeah let's fix pylint and fix pypy later.

**Pull request merged**
