### PR TITLE
Various `TryStar` fixes

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
- Add string visitor function for `TryStar` nodes.
- Add `TryStar` to `ALL_NODE_CLASSES` and `__all__`

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank you ! How did you find out that this was required ? Is this just your general knowledge of what's required in astroid ?

**Comment by cdce8p** [comment]
> Thank you ! How did you find out that this was required ? Is this just your general knowledge of what's required in astroid ?

I was looking at #1867 and noticed that `TryStar` was missing in a bunch of places where `TryExcept` / `TryFinally` where (and a bit of knowledge about how the nodes work).

**Comment by cdce8p** [comment]
Seems like targeted the wrong branch though 😞 
Guess this will be merged into main after the release anyway.

**Comment by Pierre-Sassoulas** [comment]
Did you want to fix 2.15.4 ? I think it's targeted in the right branch but there was a conflict during the cherry-pick so it needs to be applied manually ?

**Comment by cdce8p** [comment]
The fix should be in both `main` and `maintenance/2.15.x`. I mistakenly targeted the later, so the backport will of course fail (this is the backport PR essentially). I just need to get these changes into `main` now, either through a merge or via a separate PR.

**Comment by Pierre-Sassoulas** [comment]
Ha, right ! Yes, let's release 2.15.4 directly then.

**Comment by Pierre-Sassoulas** [comment]
Thank you for releasing so fast, Marc 🚀 !

**Pull request merged**
