### PR TITLE
Fix RecursionError in `infer_call_result()`

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes pylint-dev/pylint#9139

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
I see nothing wrong here, but I would lie if I say I understand what was happening here :D would you mind explaining (very slowly) ?

**Comment by jacobtylerwalls** [comment]
Of course! I noticed that the recursion error reports in pylint seemed to have a line from `infer_call_result()` in common in the tracebacks, so I looked to see if there was an addressable issue there. I found that pytorch was doing something elaborate with `__call__` that was causing astroid to get stuck in a loop, evaluating the result of a call to `__call__`.

I edited the test to show this more clearly. Inferring the result of `A.__call__()` requires... evaluating the result of `A()`, which  requires inferring the result of `A.__call__()`, ...

If you comment out the code change and run the test, you'll see the recursive calls in the pytest output:
```py
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
astroid/bases.py:334: in infer_call_result
    for res in node.infer_call_result(caller, context):
```

The point of the patch is to notice that the two things being checked are the same class and bail out.

**Comment by jacobtylerwalls** [comment]
(The `self` and `node` are both Instances of A, and the `._proxied` on each is the ClassDef for A they have in common.)

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank you for explaining, make sense !

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
(Sorry forgot to approve)

**Pull request merged**
