### PR TITLE
Assert parent is not None

### PR DESCRIPTION
**Pull request by nickdrozd**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Fixes one Mypy error.

### CODE REVIEW

**Review by DanielNoord — CHANGES_REQUESTED** [review]
I think we should think about making this some sort of generic attribute of `NodeNG`. There are lots of nodes where we know that `parent` is not `None`. Not having to put asserts everywhere would be much better, but I haven't had the time to look into how to do this properly.

**Comment by nickdrozd** [comment]
As far as assertions go, I think it's worth adding them if it helps getting Mypy running without errors.

**Comment by DanielNoord** [comment]
> When is it possible for there to be no parent? Just for modules?

I think so, but also for nodes that are constructed out of thin air. We do that quite often.



> As far as assertions go, I think it's worth adding them if it helps getting Mypy running without errors.

I don't think so. Asserts change behaviour and can make `pylint` crash. We should only add them if we know they are true and can't find any other way to express what they are testing.

**Comment by jacobtylerwalls** [comment]
> I think so, but also for nodes that are constructed out of thin air. We do that quite often.

The brains do this all over the place, see https://github.com/pylint-dev/astroid/issues/1490#issuecomment-1152619493.

**Pull request closed without merging**
