### PR TITLE
Add compatibility with python 3.13.1

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description
Refs https://github.com/python/cpython/pull/125415
Closes pylint-dev/pylint#10112

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
@Pierre-Sassoulas how do you feel about xfailing those 3 failing deque tests on python 3.13? We need to get some sort of hotfix out and I can't commit to debugging them.

**Review by Pierre-Sassoulas — APPROVED** [review]
Great work ! I think the pylint job is expected to fail and I rerun the python 3.9 job that failed with a core dump due to solar flares

**Comment by jacobtylerwalls** [comment]
@Pierre-Sassoulas Well, now I'm doubtful this accomplished anything because I'm having trouble reproducing the original issue. Ugh. I have no idea how to proceed.

**Comment by Pierre-Sassoulas** [comment]
Should we create a brain for ``collection.abc`` when the python interpreter is > 3.13.1 ? Feels dirty but we might not have a choice.

**Comment by jacobtylerwalls** [comment]
Well that's what I tried, but it didn't make a difference. At a loss until I can repro the problem.

**Comment by jacobtylerwalls** [comment]
okay, progress.

verified everything still [fails](https://github.com/jacobtylerwalls/pylint/actions/runs/12222971993/job/34093949244) with 3.13.6 (not a big deal, haven't updated pylint yet)

but pylint job [passes](https://github.com/jacobtylerwalls/pylint/actions/runs/12222910108/job/34093801363) with [this](https://github.com/jacobtylerwalls/astroid/commit/f8c52bb068f3463eb9b1d62ecd2afab3a810cf1f) commit adding a brain for the underlying `_collections_abc`.

**Comment by jacobtylerwalls** [comment]
never mind, that job was running python 3.12 for some reason. back to square one.

**Pull request merged**
