### PR TITLE
Upgrade pylint in pre-commit config

### PR DESCRIPTION
**Pull request by jacobtylerwalls**

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Comment by Pierre-Sassoulas** [comment]
Look like the suppression is not useless in the CI

**Comment by jacobtylerwalls** [comment]
Where do we bump the astroid version in the pre-commit config for pylint?

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
Waiting on #2441 being merged to squash this.

**Pull request merged**
